services:
    instant:
        image: "terran/instantid"
        volumes:
            - .:/app
        working_dir: /app
        command: uvicorn 'app:run' --port 8888 --reload --host 0.0.0.0
        ports:
            - 8000:8888
        environment:
            - SAM_HOST=http://age:5000
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]