x-proxy_settings: &proxy_settings
    HTTP_PROXY: http://192.168.50.38:1087
    HTTPS_PROXY: http://192.168.50.38:1087
    ALL_PROXY: socks5://192.168.50.38:1080

services:
    instant:
        image: "terran/instantid"
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        working_dir: /app
        command: uvicorn 'app:run' --port 8888 --reload --host 0.0.0.0
        ports:
            - 8000:8888
        environment:
            <<: *proxy_settings
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
